CREATE TABLE [cis_delta].[batch_transactions] (
    [batch_number]           NUMERIC (18)    NOT NULL,
    [transaction_number]     NUMERIC (18)    NOT NULL,
    [contact_number]         NUMERIC (18)    NOT NULL,
    [address_number]         NUMERIC (18)    NOT NULL,
    [transaction_date]       DATETIME        NOT NULL,
    [transaction_type]       VARCHAR (3)     NOT NULL,
    [bank_details_number]    NUMERIC (18)    NULL,
    [amount]                 NUMERIC (9, 2)  NOT NULL,
    [currency_amount]        NUMERIC (13, 2) NULL,
    [payment_method]         VARCHAR (4)     NOT NULL,
    [reference]              VARCHAR (18)    NULL,
    [next_line_number]       NUMERIC (18)    NULL,
    [line_total]             NUMERIC (9, 2)  NOT NULL,
    [mailing]                VARCHAR (15)    NULL,
    [receipt]                VARCHAR (1)     NOT NULL,
    [mailing_contact_number] NUMERIC (18)    NULL,
    [mailing_address_number] NUMERIC (18)    NULL,
    [amended_by]             VARCHAR (14)    NOT NULL,
    [amended_on]             DATETIME        NOT NULL,
    [eligible_for_gift_aid]  VARCHAR (1)     NULL,
    [transaction_origin]     VARCHAR (10)    NULL,
    [notes]                  VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_batch_transactions_1] PRIMARY KEY CLUSTERED ([batch_number] ASC, [transaction_number] ASC, [contact_number] ASC)
);

