CREATE TABLE [cis_delta].[contact_legacies] (
    [legacy_number]             NUMERIC (18)   NOT NULL,
    [contact_number]            NUMERIC (18)   NOT NULL,
    [legacy_id]                 VARCHAR (20)   NULL,
    [legacy_status]             VARCHAR (4)    NOT NULL,
    [source]                    VARCHAR (10)   NOT NULL,
    [source_date]               DATETIME       NOT NULL,
    [will_date]                 DATETIME       NULL,
    [last_codicil_date]         DATETIME       NULL,
    [gross_estate_value]        NUMERIC (9, 2) NULL,
    [net_estate_value]          NUMERIC (9, 2) NULL,
    [total_estimated_value]     NUMERIC (9, 2) NULL,
    [date_of_death]             DATETIME       NULL,
    [death_notification_source] NUMERIC (18)   NULL,
    [death_notification_date]   DATETIME       NULL,
    [date_of_probate]           DATETIME       NULL,
    [next_bequest_number]       NUMERIC (18)   NOT NULL,
    [amended_by]                VARCHAR (14)   NOT NULL,
    [amended_on]                DATETIME       NOT NULL,
    [admin_expenses_value]      NUMERIC (9, 2) NULL,
    [tax_value]                 NUMERIC (9, 2) NULL,
    [other_bequests_value]      NUMERIC (9, 2) NULL,
    [net_for_probate]           NUMERIC (9, 2) NULL,
    [liabilities_value]         NUMERIC (9, 2) NULL,
    [master_action]             NUMERIC (18)   NULL,
    [review_date]               DATETIME       NULL,
    [legacy_review_reason]      VARCHAR (4)    NULL,
    [agency_notification_date]  DATETIME       NULL,
    [accounts_received]         DATETIME       NULL,
    [accounts_approved]         DATETIME       NULL,
    [age_at_death]              NUMERIC (18)   NULL,
    [lead_charity]              VARCHAR (1)    NOT NULL,
    [in_dispute]                VARCHAR (1)    NOT NULL,
    [legacy_dispute_reason]     VARCHAR (4)    NULL
);

