CREATE TABLE [cis_delta].[contacts] (
    [contact_number]         NUMERIC (18)   NOT NULL,
    [title]                  VARCHAR (40)   NULL,
    [forenames]              VARCHAR (60)   NULL,
    [initials]               VARCHAR (7)    NULL,
    [surname]                VARCHAR (50)   NOT NULL,
    [honorifics]             VARCHAR (30)   NULL,
    [salutation]             VARCHAR (80)   NULL,
    [label_name]             VARCHAR (80)   NOT NULL,
    [preferred_forename]     VARCHAR (30)   NULL,
    [sex]                    VARCHAR (1)    NOT NULL,
    [source]                 VARCHAR (10)   NOT NULL,
    [source_date]            DATETIME       NOT NULL,
    [name_gathering_source]  VARCHAR (10)   NULL,
    [date_of_birth]          DATETIME       NULL,
    [status]                 VARCHAR (4)    NULL,
    [status_date]            DATETIME       NULL,
    [status_reason]          VARCHAR (80)   NULL,
    [department]             VARCHAR (4)    NOT NULL,
    [address_number]         NUMERIC (18)   NOT NULL,
    [dialling_code]          VARCHAR (5)    NULL,
    [std_code]               VARCHAR (8)    NULL,
    [telephone]              VARCHAR (20)   NULL,
    [ex_directory]           VARCHAR (1)    NULL,
    [notes]                  VARCHAR (MAX)  NULL,
    [contact_vat_category]   VARCHAR (1)    NOT NULL,
    [amended_by]             VARCHAR (14)   NOT NULL,
    [amended_on]             DATETIME       NOT NULL,
    [contact_type]           VARCHAR (1)    NOT NULL,
    [dob_estimated]          VARCHAR (1)    NULL,
    [contact_group]          VARCHAR (4)    NULL,
    [ownership_group]        VARCHAR (4)    NULL,
    [prefix_honorifics]      VARCHAR (30)   NULL,
    [surname_prefix]         VARCHAR (10)   NULL,
    [informal_salutation]    VARCHAR (80)   NULL,
    [ni_number]              VARCHAR (9)    NULL,
    [label_name_format_code] VARCHAR (8)    NULL,
    [ELTAction]              INT            NULL,
    [CIS_CHECKSUM]           VARBINARY (16) NULL
);

