CREATE TABLE [cis_delta].[gaye_pledges] (
    [gaye_pledge_number]          NUMERIC (18)   NOT NULL,
    [contact_number]              NUMERIC (18)   NOT NULL,
    [organisation_number]         NUMERIC (18)   NOT NULL,
    [agency_number]               NUMERIC (18)   NOT NULL,
    [donor_id]                    NUMERIC (18)   NULL,
    [pfo_code]                    VARCHAR (10)   NULL,
    [work_address_number]         NUMERIC (18)   NULL,
    [paybill_address_number]      NUMERIC (18)   NULL,
    [pledge_amount]               NUMERIC (9, 2) NOT NULL,
    [donor_total]                 NUMERIC (9, 2) NOT NULL,
    [employer_total]              NUMERIC (9, 2) NOT NULL,
    [government_total]            NUMERIC (9, 2) NOT NULL,
    [admin_fees_total]            NUMERIC (9, 2) NOT NULL,
    [net_total]                   NUMERIC (9, 2) NOT NULL,
    [start_date]                  DATETIME       NOT NULL,
    [source]                      VARCHAR (10)   NOT NULL,
    [product]                     VARCHAR (20)   NOT NULL,
    [rate]                        VARCHAR (4)    NOT NULL,
    [cancellation_reason]         VARCHAR (4)    NULL,
    [cancelled_on]                DATETIME       NULL,
    [cancelled_by]                VARCHAR (14)   NULL,
    [distribution_code]           VARCHAR (10)   NULL,
    [payroll_number]              VARCHAR (30)   NULL,
    [amended_by]                  VARCHAR (14)   NOT NULL,
    [amended_on]                  DATETIME       NOT NULL,
    [payroll_organisation_number] NUMERIC (18)   NULL,
    [cancellation_source]         VARCHAR (10)   NULL,
    [last_payment_date]           DATETIME       NULL,
    [payment_frequency]           VARCHAR (1)    NULL,
    [payment_number]              NUMERIC (18)   NOT NULL,
    [address_number]              NUMERIC (18)   NULL,
    [created_by]                  VARCHAR (14)   NULL,
    [created_on]                  DATETIME       NULL
);

