CREATE TABLE [cis_delta].[gaye_controls] (
    [donor_product]                  VARCHAR (20) NOT NULL,
    [donor_rate]                     VARCHAR (4)  NOT NULL,
    [employer_product]               VARCHAR (20) NULL,
    [employer_rate]                  VARCHAR (4)  NULL,
    [government_product]             VARCHAR (20) NULL,
    [government_rate]                VARCHAR (4)  NULL,
    [admin_fee_product]              VARCHAR (20) NULL,
    [admin_fee_rate]                 VARCHAR (4)  NULL,
    [gaye_pledge_activity]           VARCHAR (6)  NULL,
    [gaye_pledge_activity_value]     VARCHAR (4)  NULL,
    [government_percentage]          NUMERIC (18) NOT NULL,
    [source]                         VARCHAR (10) NOT NULL,
    [ni_data_source]                 VARCHAR (4)  NOT NULL,
    [distribution_code]              VARCHAR (10) NULL,
    [employer_agency_relationship]   VARCHAR (4)  NULL,
    [employer_payroll_relationship]  VARCHAR (4)  NULL,
    [post_tax_donor_product]         VARCHAR (20) NULL,
    [post_tax_donor_rate]            VARCHAR (4)  NULL,
    [post_tax_employer_product]      VARCHAR (20) NULL,
    [post_tax_employer_rate]         VARCHAR (4)  NULL,
    [post_tax_pledge_source]         VARCHAR (10) NULL,
    [post_tax_distribution_code]     VARCHAR (4)  NULL,
    [post_tax_employer_activity]     VARCHAR (6)  NULL,
    [post_tax_employer_act_value]    VARCHAR (4)  NULL,
    [post_tax_empr_payroll_relation] VARCHAR (4)  NULL,
    [post_tax_pledge_activity]       VARCHAR (6)  NULL,
    [post_tax_pledge_activity_value] VARCHAR (4)  NULL
);

