CREATE TABLE [cis_delta].[orders] (
    [order_number]                NUMERIC (18)   NOT NULL,
    [order_type]                  VARCHAR (1)    NOT NULL,
    [contact_number]              NUMERIC (18)   NOT NULL,
    [address_number]              NUMERIC (18)   NOT NULL,
    [order_date]                  DATETIME       NOT NULL,
    [order_term]                  NUMERIC (18)   NOT NULL,
    [order_term_units]            VARCHAR (1)    NULL,
    [renewal_date]                DATETIME       NOT NULL,
    [expiry_date]                 DATETIME       NOT NULL,
    [payment_method]              VARCHAR (4)    NOT NULL,
    [payment_frequency]           VARCHAR (1)    NOT NULL,
    [frequency_amount]            NUMERIC (9, 2) NOT NULL,
    [amount]                      NUMERIC (9, 2) NULL,
    [balance]                     NUMERIC (9, 2) NOT NULL,
    [arrears]                     NUMERIC (9, 2) NOT NULL,
    [in_advance]                  NUMERIC (9, 2) NOT NULL,
    [renewal_amount]              NUMERIC (9, 2) NOT NULL,
    [last_payment]                NUMERIC (9, 2) NULL,
    [last_payment_date]           DATETIME       NULL,
    [next_payment_due]            DATETIME       NOT NULL,
    [bankers_order]               VARCHAR (1)    NOT NULL,
    [direct_debit]                VARCHAR (1)    NOT NULL,
    [covenant]                    VARCHAR (1)    NOT NULL,
    [credit_card]                 VARCHAR (1)    NOT NULL,
    [detail_lines]                NUMERIC (18)   NOT NULL,
    [next_detail_line]            NUMERIC (18)   NOT NULL,
    [payment_number]              NUMERIC (18)   NOT NULL,
    [number_of_reminders]         NUMERIC (18)   NOT NULL,
    [cancellation_reason]         VARCHAR (4)    NULL,
    [cancelled_on]                DATE           NULL,
    [cancelled_by]                VARCHAR (14)   NULL,
    [reason_for_despatch]         VARCHAR (4)    NULL,
    [branch]                      VARCHAR (4)    NULL,
    [membership_type]             VARCHAR (4)    NULL,
    [source]                      VARCHAR (10)   NULL,
    [their_reference]             VARCHAR (80)   NULL,
    [amended_by]                  VARCHAR (14)   NOT NULL,
    [amended_on]                  DATETIME       NOT NULL,
    [renewal_pending]             VARCHAR (1)    NOT NULL,
    [gift_membership]             VARCHAR (1)    NOT NULL,
    [one_year_gift]               VARCHAR (1)    NOT NULL,
    [future_cancellation_date]    DATETIME       NULL,
    [future_cancellation_reason]  VARCHAR (4)    NULL,
    [sales_contact_number]        NUMERIC (18)   NULL,
    [sales_group]                 VARCHAR (6)    NULL,
    [reprint]                     VARCHAR (1)    NULL,
    [renewal_change_reason]       VARCHAR (4)    NULL,
    [renewal_changed_by]          VARCHAR (14)   NULL,
    [renewal_changed_on]          DATETIME       NULL,
    [renewal_change_value]        NUMERIC (18)   NULL,
    [reset_order_term]            VARCHAR (1)    NULL,
    [cancellation_source]         VARCHAR (10)   NULL,
    [future_cancellation_source]  VARCHAR (10)   NULL,
    [provisional]                 VARCHAR (1)    NULL,
    [giver_contact_number]        NUMERIC (18)   NULL,
    [created_by]                  VARCHAR (14)   NULL,
    [created_on]                  DATETIME       NULL,
    [confirmed_on]                DATETIME       NULL,
    [first_amount]                NUMERIC (9, 2) NULL,
    [payment_schedule_amended_on] DATETIME       NULL,
    [claim_day]                   NUMERIC (18)   NULL,
    [eligible_for_gift_aid]       VARCHAR (1)    NULL,
    [pack_to_member]              VARCHAR (1)    NOT NULL,
    [one_off_payment]             VARCHAR (1)    NOT NULL,
    [start_month]                 NUMERIC (18)   NULL
);

