CREATE TABLE [cis_delta].[sessions] (
    [event_number]            NUMERIC (18)   NOT NULL,
    [session_number]          NUMERIC (18)   NOT NULL,
    [session_desc]            VARCHAR (60)   NOT NULL,
    [session_type]            VARCHAR (4)    NOT NULL,
    [subject]                 VARCHAR (20)   NOT NULL,
    [skill_level]             VARCHAR (4)    NOT NULL,
    [start_date]              DATETIME       NOT NULL,
    [end_date]                DATETIME       NOT NULL,
    [start_time]              VARCHAR (5)    NOT NULL,
    [end_time]                VARCHAR (5)    NOT NULL,
    [location]                VARCHAR (255)  NULL,
    [minimum_attendees]       NUMERIC (18)   NOT NULL,
    [maximum_attendees]       NUMERIC (18)   NOT NULL,
    [target_attendees]        NUMERIC (18)   NOT NULL,
    [number_interested]       NUMERIC (18)   NOT NULL,
    [number_of_attendees]     NUMERIC (18)   NOT NULL,
    [number_on_waiting_list]  NUMERIC (18)   NULL,
    [maximum_on_waiting_list] NUMERIC (18)   NULL,
    [notes]                   VARCHAR (MAX)  NULL,
    [venue_booking_number]    NUMERIC (18)   NULL,
    [cpd_approval_status]     VARCHAR (1)    NULL,
    [cpd_awarding_body]       VARCHAR (40)   NULL,
    [cpd_category]            VARCHAR (4)    NULL,
    [cpd_year]                NUMERIC (18)   NULL,
    [cpd_points]              NUMERIC (18)   NULL,
    [cpd_notes]               VARCHAR (2000) NULL,
    [amended_by]              VARCHAR (14)   NOT NULL,
    [amended_on]              DATETIME       NOT NULL,
    [cpd_date_approved]       DATETIME       NULL,
    [long_description]        VARCHAR (200)  NULL,
    [external_appointment_id] VARCHAR (256)  NULL
);

