CREATE PROCEDURE [cis].[usp_Merge_events]
AS 
BEGIN

BEGIN TRY
    BEGIN TRANSACTION;

--Synchronize the target table with
--refreshed data from source table
MERGE cis.[events]  AS t
USING cis_delta.[events]  AS s 
ON (t.[event_number] = s.[event_number]) 
--When records are matched, update 
--the records if there is any change
WHEN NOT MATCHED BY TARGET 
    THEN INSERT(
		[event_number]
      ,[event_desc]
      ,[venue]
      ,[venue_reference]
      ,[venue_confirmed]
      ,[venue_confirmed_by]
      ,[branch]
      ,[start_date]
      ,[external]
      ,[attendees_checked]
      ,[evaluations_processed]
      ,[cancellation_reason]
      ,[cancelled_on]
      ,[cancelled_by]
      ,[booking]
      ,[bookings_close]
      ,[multi_session]
      ,[free_of_charge]
      ,[next_session_number]
      ,[next_booking_number]
      ,[next_option_number]
      ,[source]
      ,[amended_on]
      ,[amended_by]
      ,[qp_form_type]
      ,[qp_link_number]
      ,[template]
      ,[move_session_dates]
      ,[master_action]
      ,[event_reference]
      ,[candidate_numbering_method]
      ,[first_candidate_number]
      ,[candidate_number_block_size]
      ,[eligibility_check_required]
      ,[eligibility_check_text]
      ,[deferred_booking_act]
      ,[deferred_booking_act_value]
      ,[rejected_booking_act]
      ,[rejected_booking_act_value]
      ,[department]
      ,[event_status]
      ,[charge_for_waiting]
      ,[waiting_list_control_method]
      ,[event_group]
      ,[long_description]
      ,[event_class]
      ,[activity_group]
      ,[relationship_group]
      ,[target_income]
      ,[sponsored_costs]
      ,[sponsorship_income]
      ,[donation_income]
      ,[booking_income]
      ,[other_income]
      ,[total_income]
      ,[total_costs]
      ,[total_expenditure]
      ,[return_on_investment]
      ,[delegate_contribution]
      ,[gift_aid_declaration_count]
      ,[gift_aid_declaration_value]
      ,[financial_last_calculated]
      ,[balance_booking_fee]
      ,[balance_booking_due]
      ,[minimum_sponsorship_amount]
      ,[sponsorship_due]
      ,[pledged_amount_due]
      ,[sponsorship_last_calculated]
      ,[sponsorship_product]
      ,[sponsorship_rate]
      ,[number_of_bookings]
      ,[name_attendees]
      ,[event_pricing_matrix]
      ,[web_publish]
      ,[admin_email_address])
	
VALUES(

	   s.[event_number]
      ,s.[event_desc]
      ,s.[venue]
      ,s.[venue_reference]
      ,s.[venue_confirmed]
      ,s.[venue_confirmed_by]
      ,s.[branch]
      ,s.[start_date]
      ,s.[external]
      ,s.[attendees_checked]
      ,s.[evaluations_processed]
      ,s.[cancellation_reason]
      ,s.[cancelled_on]
      ,s.[cancelled_by]
      ,s.[booking]
      ,s.[bookings_close]
      ,s.[multi_session]
      ,s.[free_of_charge]
      ,s.[next_session_number]
      ,s.[next_booking_number]
      ,s.[next_option_number]
      ,s.[source]
      ,s.[amended_on]
      ,s.[amended_by]
      ,s.[qp_form_type]
      ,s.[qp_link_number]
      ,s.[template]
      ,s.[move_session_dates]
      ,s.[master_action]
      ,s.[event_reference]
      ,s.[candidate_numbering_method]
      ,s.[first_candidate_number]
      ,s.[candidate_number_block_size]
      ,s.[eligibility_check_required]
      ,s.[eligibility_check_text]
      ,s.[deferred_booking_act]
      ,s.[deferred_booking_act_value]
      ,s.[rejected_booking_act]
      ,s.[rejected_booking_act_value]
      ,s.[department]
      ,s.[event_status]
      ,s.[charge_for_waiting]
      ,s.[waiting_list_control_method]
      ,s.[event_group]
      ,s.[long_description]
      ,s.[event_class]
      ,s.[activity_group]
      ,s.[relationship_group]
      ,s.[target_income]
      ,s.[sponsored_costs]
      ,s.[sponsorship_income]
      ,s.[donation_income]
      ,s.[booking_income]
      ,s.[other_income]
      ,s.[total_income]
      ,s.[total_costs]
      ,s.[total_expenditure]
      ,s.[return_on_investment]
      ,s.[delegate_contribution]
      ,s.[gift_aid_declaration_count]
      ,s.[gift_aid_declaration_value]
      ,s.[financial_last_calculated]
      ,s.[balance_booking_fee]
      ,s.[balance_booking_due]
      ,s.[minimum_sponsorship_amount]
      ,s.[sponsorship_due]
      ,s.[pledged_amount_due]
      ,s.[sponsorship_last_calculated]
      ,s.[sponsorship_product]
      ,s.[sponsorship_rate]
      ,s.[number_of_bookings]
      ,s.[name_attendees]
      ,s.[event_pricing_matrix]
      ,s.[web_publish]
      ,s.[admin_email_address])
WHEN MATCHED 
    THEN UPDATE SET
		
	t.[event_number] = s.[event_number]
      ,t.[event_desc] = s.[event_desc]
      ,t.[venue] = s.[venue]
      ,t.[venue_reference] = s.[venue_reference]
      ,t.[venue_confirmed] = s.[venue_confirmed]
      ,t.[venue_confirmed_by] = s.[venue_confirmed_by]
      ,t.[branch] = s.[branch]
      ,t.[start_date] = s.[start_date]
      ,t.[external] = s.[external]
      ,t.[attendees_checked] = s.[attendees_checked]
      ,t.[evaluations_processed] = s.[evaluations_processed]
      ,t.[cancellation_reason] = s.[cancellation_reason]
      ,t.[cancelled_on] = s.[cancelled_on]
      ,t.[cancelled_by] = s.[cancelled_by]
      ,t.[booking] = s.[booking]
      ,t.[bookings_close] = s.[bookings_close]
      ,t.[multi_session] = s.[multi_session]
      ,t.[free_of_charge] = s.[free_of_charge]
      ,t.[next_session_number] = s.[next_session_number]
      ,t.[next_booking_number] = s.[next_booking_number]
      ,t.[next_option_number] = s.[next_option_number]
      ,t.[source] = s.[source]
      ,t.[amended_on] = s.[amended_on]
      ,t.[amended_by] = s.[amended_by]
      ,t.[qp_form_type] = s.[qp_form_type]
      ,t.[qp_link_number] = s.[qp_link_number]
      ,t.[template] = s.[template]
      ,t.[move_session_dates] = s.[move_session_dates]
      ,t.[master_action] = s.[master_action]
      ,t.[event_reference] = s.[event_reference]
      ,t.[candidate_numbering_method] = s.[candidate_numbering_method]
      ,t.[first_candidate_number] = s.[first_candidate_number]
      ,t.[candidate_number_block_size] = s.[candidate_number_block_size]
      ,t.[eligibility_check_required] = s.[eligibility_check_required]
      ,t.[eligibility_check_text] = s.[eligibility_check_text]
      ,t.[deferred_booking_act] = s.[deferred_booking_act]
      ,t.[deferred_booking_act_value] = s.[deferred_booking_act_value]
      ,t.[rejected_booking_act] = s.[rejected_booking_act]
      ,t.[rejected_booking_act_value] = s.[rejected_booking_act_value]
      ,t.[department] = s.[department]
      ,t.[event_status] = s.[event_status]
      ,t.[charge_for_waiting] = s.[charge_for_waiting]
      ,t.[waiting_list_control_method] = s.[waiting_list_control_method]
      ,t.[event_group] = s.[event_group]
      ,t.[long_description] = s.[long_description]
      ,t.[event_class] = s.[event_class]
      ,t.[activity_group] = s.[activity_group]
      ,t.[relationship_group] = s.[relationship_group]
      ,t.[target_income] = s.[target_income]
      ,t.[sponsored_costs] = s.[sponsored_costs]
      ,t.[sponsorship_income] = s.[sponsorship_income]
      ,t.[donation_income] = s.[donation_income]
      ,t.[booking_income] = s.[booking_income]
      ,t.[other_income] = s.[other_income]
      ,t.[total_income] = s.[total_income]
      ,t.[total_costs] = s.[total_costs]
      ,t.[total_expenditure] = s.[total_expenditure]
      ,t.[return_on_investment] = s.[return_on_investment]
      ,t.[delegate_contribution] = s.[delegate_contribution]
      ,t.[gift_aid_declaration_count] = s.[gift_aid_declaration_count]
      ,t.[gift_aid_declaration_value] = s.[gift_aid_declaration_value]
      ,t.[financial_last_calculated] = s.[financial_last_calculated]
      ,t.[balance_booking_fee] = s.[balance_booking_fee]
      ,t.[balance_booking_due] = s.[balance_booking_due]
      ,t.[minimum_sponsorship_amount] = s.[minimum_sponsorship_amount]
      ,t.[sponsorship_due] = s.[sponsorship_due]
      ,t.[pledged_amount_due] = s.[pledged_amount_due]
      ,t.[sponsorship_last_calculated] = s.[sponsorship_last_calculated]
      ,t.[sponsorship_product] = s.[sponsorship_product]
      ,t.[sponsorship_rate] = s.[sponsorship_rate]
      ,t.[number_of_bookings] = s.[number_of_bookings]
      ,t.[name_attendees] = s.[name_attendees]
      ,t.[event_pricing_matrix] = s.[event_pricing_matrix]
      ,t.[web_publish] = s.[web_publish]
      ,t.[admin_email_address] = s.[admin_email_address]

	  ; 
	  		 COMMIT TRANSACTION;
  END TRY
  BEGIN CATCH
    IF @@TRANCOUNT > 0
    ROLLBACK TRANSACTION;
 
    DECLARE @ErrorNumber INT = ERROR_NUMBER();
    DECLARE @ErrorLine INT = ERROR_LINE();
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
 

	INSERT INTO [control].[TableErrors]

	SELECT 'cis.events' as TableName, getdate() as LoadDate, 
     CAST(@ErrorNumber AS VARCHAR(10)) as ErrNum,  CAST(@ErrorLine AS VARCHAR(10)) as ErrLne, 
	 CAST(@ErrorMessage as VARCHAR(MAX)) as ErrMsg;
 
    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
  END CATCH

	END
	
	
