CREATE TABLE [dbo].[DimContact] (
    [PK_ID]                         INT          IDENTITY (1, 1) NOT NULL,
    [title]                         VARCHAR (40) NOT NULL,
    [initials]                      VARCHAR (7)  NOT NULL,
    [forename]                      VARCHAR (60) NOT NULL,
    [preferred_forename]            VARCHAR (30) NOT NULL,
    [surname]                       VARCHAR (50) NOT NULL,
    [label_name]                    VARCHAR (80) NOT NULL,
    [CISContactNumber]              INT          NULL,
    [honorifics]                    VARCHAR (30) NOT NULL,
    [salutation]                    VARCHAR (80) NULL,
    [dob]                           DATETIME     NULL,
    [Age]                           INT          NULL,
    [isUnder18]                     INT          NOT NULL,
    [age_band]                      VARCHAR (10) NULL,
    [sex]                           VARCHAR (1)  NOT NULL,
    [LengthOfRelationshipId]        INT          NOT NULL,
    [LengthOfRelationship]          VARCHAR (7)  NOT NULL,
    [EthnicityId]                   VARCHAR (4)  NOT NULL,
    [EthnicityTypeDesc]             VARCHAR (60) NOT NULL,
    [DiabetesTypeValue]             VARCHAR (4)  NOT NULL,
    [DiabetesTypeDesc]              VARCHAR (25) NOT NULL,
    [source]                        VARCHAR (10) NOT NULL,
    [source_date]                   DATETIME     NOT NULL,
    [status]                        VARCHAR (4)  NOT NULL,
    [status_date]                   DATETIME     NOT NULL,
    [status_reaso]                  VARCHAR (80) NOT NULL,
    [contact_type]                  VARCHAR (1)  NOT NULL,
    [ownership_group]               VARCHAR (4)  NULL,
    [branch]                        VARCHAR (4)  NOT NULL,
    [IsActiveMembership]            INT          NOT NULL,
    [IsActiveRegularGiving]         INT          NOT NULL,
    [IsActiveWeeklyLottery]         INT          NOT NULL,
    [IsActiveCash]                  INT          NOT NULL,
    [IsActiveRaffle]                INT          NOT NULL,
    [IsActiveFreePrizeDraw]         INT          NOT NULL,
    [IsActiveInMemory]              INT          NOT NULL,
    [IsActivePayrollGiving]         INT          NOT NULL,
    [ActiveFinancialRelationships]  INT          NULL,
    [CommittmentValue]              FLOAT (53)   NOT NULL,
    [CommittmentValueId]            INT          NOT NULL,
    [CommittmentValueDesc]          VARCHAR (9)  NOT NULL,
    [CommittmentValueMembership]    FLOAT (53)   NOT NULL,
    [CommittmentValueRegularGiving] FLOAT (53)   NOT NULL,
    [CommittmentValueWeeklyLottery] FLOAT (53)   NOT NULL,
    [PrevYearTransactionAmount]     FLOAT (53)   NOT NULL,
    [Prev2YearTransactionAmount]    FLOAT (53)   NOT NULL,
    [Prev3YearTransactionAmount]    FLOAT (53)   NOT NULL,
    [Prev4YearTransactionAmount]    FLOAT (53)   NOT NULL,
    [Prev5YearTransactionAmount]    FLOAT (53)   NOT NULL,
    [TotalTransactionAmount]        FLOAT (53)   NOT NULL,
    [LastPaymentTimeframeId]        INT          NOT NULL,
    [LastPaymentTimeframeDesc]      VARCHAR (15) NOT NULL,
    [LegacyHierarchy]               INT          NULL,
    [LegacyHierarchyDesc]           VARCHAR (40) NULL,
    [DW_LoadDate]                   DATETIME     NULL,
    CONSTRAINT [PK_DimContact] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);

