CREATE TABLE [dbo].[DimDate] (
    [DateKey]                 INT          NOT NULL,
    [Date]                    DATETIME     NULL,
    [FullDateUK]              VARCHAR (10) NULL,
    [FullDateUSA]             VARCHAR (10) NULL,
    [DayOfMonth]              INT          NULL,
    [DaySuffix]               VARCHAR (4)  NULL,
    [DayName]                 VARCHAR (9)  NOT NULL,
    [DayOfWeekUSA]            INT          NULL,
    [DayOfWeekUK]             INT          NULL,
    [DayOfWeekInMonth]        INT          NULL,
    [DayOfWeekInYear]         INT          NULL,
    [DayOfQuarter]            INT          NULL,
    [DayOfYear]               INT          NULL,
    [WeekOfMonth]             INT          NULL,
    [WeekOfQuarter]           INT          NULL,
    [WeekOfYear]              INT          NULL,
    [Month]                   INT          NULL,
    [MonthName]               VARCHAR (9)  NULL,
    [MonthOfQuarter]          INT          NULL,
    [Quarter]                 INT          NULL,
    [QuarterName]             VARCHAR (9)  NULL,
    [Year]                    INT          NULL,
    [YearName]                VARCHAR (7)  NULL,
    [MonthYear]               VARCHAR (50) NULL,
    [MMYYYY]                  VARCHAR (6)  NULL,
    [FirstDayOfMonth]         DATE         NULL,
    [LastDayOfMonth]          DATE         NULL,
    [FirstDayOfQuarter]       DATE         NULL,
    [LastDayOfQuarter]        DATE         NULL,
    [FirstDayOfYear]          DATE         NULL,
    [LastDayOfYear]           DATE         NULL,
    [IsHolidayUSA]            BIT          NULL,
    [IsWeekday]               BIT          NULL,
    [HolidayUSA]              VARCHAR (50) NULL,
    [IsHolidayUK]             BIT          NULL,
    [HolidayUK]               VARCHAR (50) NULL,
    [FiscalDayOfYear]         INT          NULL,
    [FiscalWeekOfYear]        INT          NULL,
    [FiscalMonth]             INT          NULL,
    [FiscalQuarter]           INT          NOT NULL,
    [FiscalQuarterName]       VARCHAR (50) NULL,
    [FiscalYear]              INT          NULL,
    [FiscalYearName]          VARCHAR (3)  NULL,
    [FiscalMonthYear]         VARCHAR (10) NULL,
    [FiscalMMYYYY]            VARCHAR (10) NULL,
    [FiscalFirstDayOfMonth]   DATE         NULL,
    [FiscalLastDayOfMonth]    DATE         NULL,
    [FiscalFirstDayOfQuarter] DATE         NULL,
    [FiscalLastDayOfQuarter]  DATE         NULL,
    [FiscalFirstDayOfYear]    DATE         NULL,
    [FiscalLastDayOfYear]     DATE         NULL,
    CONSTRAINT [PK_DimDate] PRIMARY KEY CLUSTERED ([DateKey] ASC)
);

