CREATE TABLE [dbo].[DimRegion] (
    [PK_ID]                         INT           IDENTITY (1, 1) NOT NULL,
    [postcode]                      VARCHAR (10)  NOT NULL,
    [latitude]                      REAL          NOT NULL,
    [longitude]                     REAL          NOT NULL,
    [Easting]                       INT           NULL,
    [Northing]                      INT           NULL,
    [GridRef]                       VARCHAR (8)   NOT NULL,
    [County]                        VARCHAR (16)  NOT NULL,
    [District]                      VARCHAR (28)  NOT NULL,
    [Ward]                          VARCHAR (56)  NOT NULL,
    [parish]                        VARCHAR (45)  NOT NULL,
    [Country]                       VARCHAR (16)  NOT NULL,
    [Constituency]                  VARCHAR (43)  NOT NULL,
    [branch]                        VARCHAR (4)   NOT NULL,
    [branch_desc]                   VARCHAR (80)  NULL,
    [rf_area]                       NVARCHAR (10) NULL,
    [rf_area_desc]                  NVARCHAR (80) NULL,
    [fund_region]                   NVARCHAR (10) NULL,
    [fund_region_desc]              NVARCHAR (80) NULL,
    [PCO_SHA]                       VARCHAR (80)  NULL,
    [DUK_region]                    VARCHAR (80)  NULL,
    [duk_nation]                    VARCHAR (80)  NULL,
    [organisation_desc_1]           VARCHAR (80)  NULL,
    [relationship_desc_1]           VARCHAR (30)  NULL,
    [organisation_desc_2]           VARCHAR (80)  NULL,
    [relationship_desc_2]           VARCHAR (30)  NULL,
    [organisation_desc_3]           VARCHAR (80)  NOT NULL,
    [relationship_desc_3]           VARCHAR (30)  NOT NULL,
    [organisation_desc_4]           VARCHAR (80)  NOT NULL,
    [relationship_desc_4]           VARCHAR (30)  NOT NULL,
    [Lower layer super output area] VARCHAR (63)  NOT NULL,
    [Rural urban]                   VARCHAR (55)  NOT NULL,
    [population]                    SMALLINT      NOT NULL,
    [Households]                    SMALLINT      NOT NULL,
    [acorn_group]                   VARCHAR (25)  NOT NULL,
    [acorn_category]                VARCHAR (23)  NOT NULL,
    [acorn_type]                    VARCHAR (60)  NOT NULL,
    [DW_LoadDate]                   DATETIME      NULL,
    CONSTRAINT [PK_DimRegion] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);

