CREATE TABLE [dbo].[DimSource] (
    [PK_ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [source]                   VARCHAR (10)   NULL,
    [source_desc]              VARCHAR (60)   NULL,
    [incentive_trigger_level]  NUMERIC (9, 2) NULL,
    [thank_you_letter]         VARCHAR (15)   NULL,
    [incentive_scheme]         VARCHAR (4)    NULL,
    [history_only]             VARCHAR (1)    NULL,
    [distribution_code]        VARCHAR (10)   NULL,
    [discount_percentage]      NUMERIC (5, 2) NULL,
    [df_flag]                  CHAR (1)       NULL,
    [df_batch_type]            CHAR (1)       NULL,
    [df_mapping]               VARCHAR (10)   NULL,
    [acq_source_group]         VARCHAR (4)    NULL,
    [acq_source_sub_group]     VARCHAR (4)    NULL,
    [donation_product]         VARCHAR (20)   NULL,
    [donation_rg_product]      VARCHAR (20)   NULL,
    [web_alias]                VARCHAR (20)   NULL,
    [rate]                     VARCHAR (4)    NULL,
    [num_ring_fence_days]      INT            NULL,
    [is_event]                 CHAR (1)       NULL,
    [IC_mapped_product]        VARCHAR (40)   NULL,
    [IC_mapped_region]         VARCHAR (20)   NULL,
    [new_source]               VARCHAR (10)   NULL,
    [new_source_desc]          VARCHAR (60)   NULL,
    [new_cost_centre]          VARCHAR (4)    NULL,
    [new_programme]            VARCHAR (6)    NULL,
    [creative_version]         VARCHAR (255)  NULL,
    [test_control]             VARCHAR (50)   NULL,
    [yearofcampaign]           VARCHAR (30)   NULL,
    [businessfunction]         VARCHAR (255)  NULL,
    [category]                 VARCHAR (255)  NULL,
    [ask]                      VARCHAR (255)  NULL,
    [channel]                  VARCHAR (255)  NULL,
    [campaign]                 VARCHAR (255)  NULL,
    [campaign_desc]            VARCHAR (255)  NULL,
    [campaign_type]            VARCHAR (255)  NULL,
    [campaign_year]            SMALLINT       NULL,
    [number_in_mailing]        INT            NULL,
    [cold_list_mailing_volume] INT            NULL,
    [costs]                    FLOAT (53)     NULL,
    [campaign_plain_desc]      VARCHAR (100)  NULL,
    [DW_LoadDate]              DATETIME       NULL,
    CONSTRAINT [PK_DimSources] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);

