CREATE TABLE [cis].[batches] (
    [batch_number]               NUMERIC (18)    NOT NULL,
    [batch_type]                 VARCHAR (2)     NOT NULL,
    [batch_date]                 DATETIME        NOT NULL,
    [cash_book_batch]            VARCHAR (5)     NULL,
    [bank_account]               VARCHAR (4)     NOT NULL,
    [number_of_entries]          NUMERIC (18)    NOT NULL,
    [batch_total]                NUMERIC (9, 2)  NOT NULL,
    [transaction_total]          NUMERIC (9, 2)  NOT NULL,
    [number_of_transactions]     NUMERIC (18)    NOT NULL,
    [next_transaction_number]    NUMERIC (18)    NOT NULL,
    [ready_for_banking]          VARCHAR (1)     NOT NULL,
    [paying_in_slip_printed]     VARCHAR (1)     NOT NULL,
    [posted_to_cash_book]        VARCHAR (1)     NOT NULL,
    [detail_completed]           VARCHAR (1)     NOT NULL,
    [posted_to_nominal]          VARCHAR (1)     NOT NULL,
    [picked]                     VARCHAR (1)     NOT NULL,
    [product]                    VARCHAR (20)    NULL,
    [rate]                       VARCHAR (4)     NULL,
    [source]                     VARCHAR (10)    NULL,
    [transaction_type]           VARCHAR (3)     NULL,
    [payment_method]             VARCHAR (4)     NULL,
    [paying_in_slip_number]      NUMERIC (18)    NULL,
    [currency_indicator]         VARCHAR (4)     NULL,
    [currency_batch_total]       NUMERIC (13, 2) NULL,
    [currency_transaction_total] NUMERIC (13, 2) NULL,
    [currency_exchange_rate]     NUMERIC (7, 3)  NULL,
    [amended_by]                 VARCHAR (14)    NOT NULL,
    [amended_on]                 DATETIME        NOT NULL,
    [journal_number]             NUMERIC (18)    NULL,
    [batch_category]             VARCHAR (4)     NULL,
    [balanced_by]                VARCHAR (14)    NULL,
    [balanced_on]                DATETIME        NULL,
    [posted_by]                  VARCHAR (14)    NULL,
    [posted_on]                  DATETIME        NULL,
    [contents_amended_by]        VARCHAR (14)    NULL,
    [contents_amended_on]        DATETIME        NULL,
    [header_amended_by]          VARCHAR (14)    NULL,
    [header_amended_on]          DATETIME        NULL,
    [batch_created_by]           VARCHAR (14)    NULL,
    [batch_created_on]           DATETIME        NULL,
    [post_nominal]               VARCHAR (1)     NOT NULL,
    [job_number]                 NUMERIC (18)    NULL,
    [provisional]                VARCHAR (1)     NULL,
    [agency_number]              NUMERIC (18)    NULL,
    [claim_sent]                 DATETIME        NULL,
    [currency_code]              VARCHAR (3)     NULL,
    [batch_analysis_code]        VARCHAR (4)     NULL,
    [campaign]                   VARCHAR (6)     NULL,
    [appeal]                     VARCHAR (6)     NULL,
    [banking_date]               DATETIME        NULL
);

