CREATE TABLE [cis].[fundraising_requests] (
    [fundraising_request_number] NUMERIC (18)   NOT NULL,
    [contact_number]             NUMERIC (18)   NOT NULL,
    [request_date]               DATETIME       NOT NULL,
    [request_description]        VARCHAR (40)   NOT NULL,
    [fundraising_request_stage]  VARCHAR (4)    NOT NULL,
    [fundraising_status]         VARCHAR (4)    NULL,
    [fundraising_request_type]   VARCHAR (4)    NOT NULL,
    [source]                     VARCHAR (10)   NOT NULL,
    [target_amount]              NUMERIC (9, 2) NOT NULL,
    [pledged_amount]             NUMERIC (9, 2) NULL,
    [pledged_date]               DATETIME       NULL,
    [received_amount]            NUMERIC (9, 2) NULL,
    [received_date]              DATETIME       NULL,
    [notes]                      VARCHAR (MAX)  NULL,
    [amended_by]                 VARCHAR (14)   NOT NULL,
    [amended_on]                 DATETIME       NOT NULL,
    [expected_amount]            NUMERIC (9, 2) NULL,
    [gik_expected_amount]        NUMERIC (9, 2) NULL,
    [gik_pledged_amount]         NUMERIC (9, 2) NULL,
    [gik_pledged_date]           DATETIME       NULL,
    [total_gik_received_amount]  NUMERIC (9, 2) NULL,
    [latest_gik_received_date]   DATETIME       NULL,
    [number_of_payments]         NUMERIC (18)   NULL,
    [request_end_date]           DATETIME       NULL,
    [logname]                    VARCHAR (14)   NULL,
    [created_by]                 VARCHAR (14)   NULL,
    [created_on]                 DATETIME       NULL,
    [target_date]                DATETIME       NULL,
    [fundraising_business_type]  VARCHAR (4)    NULL
);

