CREATE TABLE [cis].[GAD_Invalid_Declaration_date] (
    [DECLARATION_NUMBER]  NUMERIC (38)  NOT NULL,
    [CONTACT_NUMBER]      NUMERIC (38)  NOT NULL,
    [DECLARATION_DATE]    DATETIME2 (7) NOT NULL,
    [DECLARATION_TYPE]    VARCHAR (1)   NOT NULL,
    [SOURCE]              VARCHAR (10)  NOT NULL,
    [CONFIRMED_ON]        DATETIME2 (7) NULL,
    [METHOD]              VARCHAR (1)   NOT NULL,
    [START_DATE]          DATETIME2 (7) NULL,
    [END_DATE]            DATETIME2 (7) NULL,
    [NOTES]               TEXT          NULL,
    [AMENDED_BY]          VARCHAR (14)  NOT NULL,
    [AMENDED_ON]          DATETIME2 (7) NOT NULL,
    [BATCH_NUMBER]        NUMERIC (38)  NULL,
    [TRANSACTION_NUMBER]  NUMERIC (38)  NULL,
    [ORDER_NUMBER]        NUMERIC (38)  NULL,
    [CANCELLATION_REASON] VARCHAR (4)   NULL,
    [CANCELLED_BY]        VARCHAR (14)  NULL,
    [CANCELLED_ON]        DATETIME2 (7) NULL,
    [CANCELLATION_SOURCE] VARCHAR (10)  NULL,
    [CREATED_BY]          VARCHAR (14)  NULL,
    [CREATED_ON]          DATETIME2 (7) NULL
);

