CREATE TABLE [cis].[gaye_payments] (
    [gaye_payment_number] NUMERIC (18)   NULL,
    [donor_name]          VARCHAR (60)   NOT NULL,
    [donor_id]            NUMERIC (18)   NOT NULL,
    [address_line_1]      VARCHAR (36)   NULL,
    [address_line_2]      VARCHAR (36)   NULL,
    [address_line_3]      VARCHAR (36)   NULL,
    [address_line_4]      VARCHAR (36)   NULL,
    [address_line_5]      VARCHAR (36)   NULL,
    [postcode]            VARCHAR (10)   NULL,
    [employer_name]       VARCHAR (60)   NOT NULL,
    [source_code]         VARCHAR (10)   NULL,
    [pfo_code]            VARCHAR (10)   NULL,
    [new_donor]           VARCHAR (1)    NOT NULL,
    [employee_donation]   NUMERIC (9, 2) NOT NULL,
    [employer_donation]   NUMERIC (9, 2) NULL,
    [gov_payment]         NUMERIC (9, 2) NULL,
    [admin_fee]           NUMERIC (9, 2) NULL,
    [no_of_donations]     NUMERIC (18)   NULL,
    [agency_number]       NUMERIC (18)   NOT NULL,
    [contact_number]      NUMERIC (18)   NULL,
    [organisation_number] NUMERIC (18)   NULL,
    [address_number]      NUMERIC (18)   NULL,
    [gaye_pledge_number]  NUMERIC (18)   NULL,
    [title]               VARCHAR (40)   NULL,
    [initials]            VARCHAR (7)    NULL,
    [forenames]           VARCHAR (30)   NULL,
    [surname]             VARCHAR (30)   NULL,
    [transaction_date]    DATETIME       NOT NULL,
    [post_batch_to_cb]    VARCHAR (1)    NOT NULL,
    [reconciled]          VARCHAR (1)    NOT NULL
);

