CREATE TABLE [cis].[rates] (
    [product]                     VARCHAR (20)    NOT NULL,
    [rate]                        VARCHAR (4)     NOT NULL,
    [current_price]               NUMERIC (11, 6) NOT NULL,
    [future_price]                NUMERIC (11, 6) NOT NULL,
    [price_change_date]           DATETIME        NOT NULL,
    [history_only]                VARCHAR (1)     NULL,
    [nominal_account_suffix]      VARCHAR (15)    NULL,
    [rate_desc]                   VARCHAR (30)    NOT NULL,
    [concessionary]               VARCHAR (1)     NOT NULL,
    [vat_exclusive]               VARCHAR (1)     NULL,
    [amended_by]                  VARCHAR (14)    NOT NULL,
    [amended_on]                  DATETIME        NOT NULL,
    [currency_code]               VARCHAR (3)     NOT NULL,
    [subsequent_nominal_suffix]   VARCHAR (15)    NULL,
    [current_price_lower_limit]   NUMERIC (11, 6) NULL,
    [current_price_upper_limit]   NUMERIC (11, 6) NULL,
    [future_price_lower_limit]    NUMERIC (11, 6) NULL,
    [future_price_upper_limit]    NUMERIC (11, 6) NULL,
    [fixed_price]                 VARCHAR (1)     NULL,
    [upper_lower_price_mandatory] VARCHAR (1)     NOT NULL,
    [days_prior_from]             NUMERIC (18)    NULL,
    [days_prior_to]               NUMERIC (18)    NULL,
    [membership_lookup_group]     VARCHAR (4)     NULL,
    [use_modifiers]               VARCHAR (1)     NULL,
    [price_is_percentage]         VARCHAR (1)     NULL,
    [web_publish]                 VARCHAR (1)     NULL
);

