/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2012 (11.0.6594)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2012
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [DBATools]    Script Date: 25/01/2018 14:14:43 ******/
CREATE DATABASE [DBATools]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBATools', FILENAME = N'E:\DEV01\DBATools.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'DBATools_log', FILENAME = N'F:\DEV01\DBATools_log.ldf' , SIZE = 51200KB , MAXSIZE = 2048GB , FILEGROWTH = 131072KB )
GO

ALTER DATABASE [DBATools] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBATools].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBATools] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBATools] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBATools] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBATools] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBATools] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBATools] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBATools] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBATools] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBATools] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBATools] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBATools] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBATools] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBATools] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBATools] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBATools] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBATools] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBATools] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBATools] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBATools] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBATools] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBATools] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBATools] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBATools] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBATools] SET  MULTI_USER 
GO

ALTER DATABASE [DBATools] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBATools] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBATools] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBATools] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBATools] SET  READ_WRITE 
GO


