-- =============================================
CREATE PROCEDURE [dbo].[PopulateDimRate]
AS
BEGIN


	  SELECT '0' as [product]
      ,'' as [rate]
      ,0  as [current_price]
      ,0 as [future_price]
      ,null as [price_change_date]
      ,null as [history_only]
      ,null as [nominal_account_suffix]
      ,'' as [rate_desc]
      ,'' as [concessionary]
      ,null as [vat_exclusive]
      ,'' as [amended_by]
      ,'' as [amended_on]
      , '' as [currency_code]
      ,null as [subsequent_nominal_suffix]
      ,null as [current_price_lower_limit]
      ,null as [current_price_upper_limit]
      ,null as [future_price_lower_limit]
      ,null as [future_price_upper_limit]
      ,null as [fixed_price]
      ,'' as [upper_lower_price_mandatory]
      ,null as [days_prior_from]
      ,null as [days_prior_to]
      ,'' as [membership_lookup_group]
      ,'' as [use_modifiers]
      ,'' as [price_is_percentage]
      ,'' as [web_publish]
	  , GETDATE() as [DW_LoadDate]

	  UNION ALL 

SELECT [product]
      ,[rate]
      ,[current_price]
      ,[future_price]
      ,[price_change_date]
      ,[history_only]
      ,[nominal_account_suffix]
      ,[rate_desc]
      ,[concessionary]
      ,[vat_exclusive]
      ,[amended_by]
      ,[amended_on]
      ,[currency_code]
      ,[subsequent_nominal_suffix]
      ,[current_price_lower_limit]
      ,[current_price_upper_limit]
      ,[future_price_lower_limit]
      ,[future_price_upper_limit]
      ,[fixed_price]
      ,[upper_lower_price_mandatory]
      ,[days_prior_from]
      ,[days_prior_to]
      ,[membership_lookup_group]
      ,[use_modifiers]
      ,[price_is_percentage]
      ,[web_publish]
	  , GETDATE() as [DW_LoadDate]
	  FROM [DiabetesDWH].[cis].[rates]

	  
END
